import {JetBrains_Mono} from "next/font/google";
import "./globals.css";
import { Variable, Weight } from "lucide-react";

// components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
const jetBrains_Mono = JetBrains_Mono({
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800"],
  variable:'--font-jetBrainsMono'
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrains_Mono.variable}>
      <Header/>
      <PageTransition> {children}</PageTransition>
     
      </body>
    </html>
  );
}
